### ISSUE TITLE
Different behaviour between Resample and UpSample

### ISSUE THREAD

**Issue by lmanan** [funkelab/gunpowder#205] opened 2024-04-07 19:59 UTC
I noticed that the `Resample` node when used with the `Scan` node adds an empty border to the resampled output. 
This artifact goes away if one is to do the same, but with the `UpSample` node instead of `Resample` node.

As an example, here I resample the _astronaut_ image from `scikit.image` by factor of 2:
```python
import zarr
from skimage import data
import gunpowder as gp

# save a zarr with channels first
raw_data = data.astronaut().transpose(2, 0, 1)
f = zarr.open("sample_data.zarr", "w")
f["raw"] = raw_data
f["raw"].attrs["resolution"] = (2, 2)
f["raw"].attrs["axis_names"] = ("c", "y", "x")

print(f"Raw data has shape {raw_data.shape}")  # (3, 512, 512)


raw = gp.ArrayKey("RAW")
raw_resampled = gp.ArrayKey("RAW_RESAMPLED")

raw_voxel_size = gp.Coordinate(2, 2)
raw_resampled_voxel_size = gp.Coordinate(1, 1)

raw_spec = gp.ArraySpec(voxel_size=raw_voxel_size, interpolatable=True)
raw_resampled_spec = gp.ArraySpec(
    voxel_size=raw_resampled_voxel_size, interpolatable=True
)

source = gp.ZarrSource(
    "sample_data.zarr",
    {raw: "raw"},
    {raw: raw_spec},
)

resample = gp.Resample(raw, raw_resampled_voxel_size, raw_resampled, ndim=2)
#upsample = gp.UpSample(raw, raw_voxel_size, raw_resampled)

scan_request = gp.BatchRequest()
scan_request[raw] = gp.Roi((0, 0), (252, 252))
scan_request[raw_resampled] = gp.Roi((0, 0), (252, 252))

f_resampled = zarr.open("resampled.zarr")
f_resampled.create_dataset(
    "raw",
    shape=(3, 1024, 1024),
    dtype=f["raw"].dtype,
)

pipeline = (
    source
    + resample
    #+ upsample
    + gp.ZarrWrite(
        output_filename="resampled.zarr", dataset_names={raw_resampled: "raw"}
    )
    + gp.Scan(scan_request)
)

request = gp.BatchRequest()
with gp.build(pipeline):
    # ...and request a batch
    batch = pipeline.request_batch(request)

f_resampled["raw"].attrs["axis_names"] = ("c", "y", "x")
f_resampled["raw"].attrs["resolution"] = (1, 1)
```
If one now looks at the dataset `raw` within `resampled.zarr`, then one sees a border in the result (see the zoomed in version of the top left corner below, where you see a one pixel wide black or empty border)

<img width="524" alt="Screenshot 2024-04-07 at 3 54 54 PM" src="https://github.com/funkelab/gunpowder/assets/34229641/852c40d5-fa9a-4c5d-aa7b-0c00150cf81e">

<img width="944" alt="Screenshot 2024-04-07 at 3 54 28 PM" src="https://github.com/funkelab/gunpowder/assets/34229641/2804fb75-0958-4a74-80f1-985247c90f5a">

This artefact goes away if one were to use the `UpSample` node instead of the `Resample` node.

**Comment by pattonw** [comment] 2024-04-09 02:18
Thank you for catching this!

Here's the cause of the boundary:
To avoid interpolation artifacts, the resample node requests an extra voxel boundary around whatever data you want to interpolate. It seems I added a step to shrink the total request-able region by one pixel so that gathering the extra data was always possible. This results in that pixel never being available and thus being left blank.

Solution:
Just remove the 1 voxel shrinkage of the total provided roi. We will have to live with potential interpolation artifacts at the boundary since there is simply no more data to use, but the interpolation artifacts are probably better than 0s.

Solution has been merged into patch-v1.3.3 branch and will be published shortly.

**Closed by pattonw** 2024-04-09 02:18 UTC
